version: '2'
services:
  data:
    image: busybox
    volumes:
      - /var/lib/mysql
  mariadb:
    image: mariadb:10.1.17
    volumes:
        - ./initdb.d:/docker-entrypoint-initdb.d
        - ./mycnf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    volumes_from:
      - data
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  redis:
    image: redis:3.2.3-alpine
    ports:
      - "6379:6379"
