// district, communes
// refs: https://en.wikipedia.org/wiki/Chamkar_Mon_District
export default {
  'Chamkar Mon District': [
    'Tonle Basak',
    'Boeng KengKang 1',
    'Boeng KengKang 2',
    'Boeng KengKang 3',
    'Oulampik',
    'Tuol Svay Prey 1',
    'Tuol Svay Prey 2',
    'Tumnob Tuek',
    'Tuol Tumpung 1',
    'Tuol Tumpung 2',
    'Boeng Trabaek',
    'Phsar Daeum Thkov',
  ],

  'Doun Penh District': [
    'Phsar Thmei 1',
    'Phsar Thmei 2',
    'Phsar Thmei 3',
    'Boeng Reang',
    'Phsar Kandal 1',
    'Phsar Kandal 2',
    'Chakto Mukh',
    'Chey Chumneah',
    'Phsar Chas',
    'Srah Chak',
    'Voat Phnum',
  ],

  'Prampir Meakkara District': [
    'Ou Ruessei 1',
    'Ou Ruessei 2',
    'Ou Ruessei 3',
    'Ou Ruessei 4',
    'Monourom',
    'Mittakpheap',
    'Veal Vong',
    'Boeng Prolit',
  ],

  'Tuol Kouk District': [
    "Phsar Depou 1",
    "Phsar Depou 2",
    "Phsar Depou 3",
    "Tuek L'ak 1",
    "Tuek L'ak 2",
    "Tuek L'ak 3",
    "Boeng Kak 1",
    "Boeng Kak 2",
    "Phsar Daeum Kor",
    "Boeng Salang",
  ],

  'Dangkao District': [
    'Dangkao',
    'Trapeang Krasang',
    'Kouk Roka',
    'Phleung Chheh Roteh',
    'Chaom Chau',
    'Kakab',
    'Samraong Kraom',
    'Prey Sa',
    'Krang Thnong',
    'Krang Pongro',
    'Prateah Lang',
    'Sak Sampov',
    'Pong Tuek',
    'Prey Veaeng',
    'Cheung Aek',
  ],

  'Mean Chey District': [
    'Stueng Mean Chey',
    'Boeng Tumpun',
    'Preaek Pra',
    'Chbar Ampov 1',
    'Chbar Ampov 2',
    'Chak Angrae Leu',
    'Chak Angrae Kraom',
    'Nirouth',
  ],

  'Ruessei Kaev District': [
    'Khmuonh',
    'Tuol Sangkae',
    'Svay Pak',
    'Kiloumaetr Lekh 6',
    'Phnom Penh Thmei',
    'Ruessei Kaev',
    'Tuek Thla',
    'Preaek Lieb',
    'Preaek Ta Sek',
    'Chrouy Changva',
    'Chrang Chamreh 1',
    'Chrang Chamreh 2',
  ],
}
